<div class="cart" style="font-family: -apple-system, BlinkMacSystemFont, Roboto, 'Fira Sans', 'Droid Sans', 'Helvetica Neue', Arial, sans-serif !important;">
    <div class="cart-top-section">
		<div class="member-question-box">
			<b>Är du avtalskund?</b> <a href="<?php echo Mage::getUrl('customer/account/logout'); ?>">Logga in</a> för att ta del av dina avtalspriser.
		</div>
        <div class="page-title title-buttons">
            <h1><?php echo $this->__('Shopping Cart') ?></h1>
			<?php if (Mage::getStoreConfig('ecomatic_collectorbank/general/customer_type') == 2) { ?>
				<div id="businesstypes" style="float:right; display:none;">
					<a class="btype active" id="b2c"><?php echo $this->__('Privat');?></a> | <a class="btype inactive" id="b2b"><?php echo $this->__('Företag');?></a>
				</div>
			<?php } ?>
        </div>
        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
        <?php echo $this->getChildHtml('form_before') ?>
		<form action="javascript:void(0)" method="post">
		<div id="area-spinner-container" class="area-spinner-container">
			<div class="spinner-animation">&nbsp;</div>
		</div>
    		 <?php echo $this->getBlockHtml('formkey'); ?>
            
                <table id="shopping-cart-table" class="data-table cart-table">
                    <col width="1" />
                    <col />
                    <col width="1" />
                <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
                    <col width="1" />
                <?php endif ?>
                <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <col width="1" />
                <?php endif; ?>
                <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <col width="1" />
                <?php endif; ?>
                    <col width="1" />
                <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <col width="1" />
                <?php endif; ?>
                <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <col width="1" />
                <?php endif; ?>
                    <col width="1" />

                <?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
                    <thead>
                        <tr>
                            <th><span class="nobr"><?php echo $this->__('Product Name') ?></span></th>
                            <th>&nbsp;</th>                          
                            <th class="a-center"><?php echo $this->__('Qty') ?></th>
                            <th class="a-right" colspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Price') ?></th>
                        </tr>
                        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                        <tr>
                            <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                            <th colspan="<?php echo $mergedCells; ?>"></th>
                            <th class="a-right"><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
                            <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
                        </tr>
                        <?php endif; ?>
                    </thead>
                   
                    <tbody>
                    <?php foreach($this->getItems() as $_item): ?>
                        <?php echo $this->getItemHtml($_item) ?>
                    <?php endforeach ?>
                    </tbody>
                </table>
                <script type="text/javascript">decorateTable('shopping-cart-table')</script>
            
        </form>
    	
        <div class="cart-forms cart-collaterals" style="display: block !important;">
            <div class="col2-set">
               
                    <?php /* Extensions placeholder */ ?>
                    <?php echo $this->getChildHtml('checkout.cart.extra') ?>
                    <?php if (!$this->getIsVirtual()): echo $this->getChildHtml('shipping'); endif; ?>
               
            </div>
            <div class="totals cart-totals">
                <?php echo $this->getChildHtml('totals'); ?>
                <?php if(!$this->hasError()): ?>
                <ul class="checkout-types">
                <?php foreach ($this->getMethods('methods') as $method): ?>
                    <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                    <li><?php echo $methodHtml; ?></li>
                    <?php endif; ?>
                <?php endforeach; ?>
                </ul>
                <?php endif; ?>
				
				<div class="discountcoupon">
					<?php echo $this->getChildHtml('coupon') ?>
				</div>
            </div>
        </div>
	</div>
	
	<?php echo $this->getChildHtml('loadiframe'); ?>  
    <?php echo $this->getChildHtml('crosssell') ?>

	
	<script type="text/javascript">
		var url_update_shoopingcart = '<?php echo $this->getUrl("checkout/cart/updatePost") ?>';
		var url_topcart = "<?php echo $this->getUrl('ajax/ajax/headercart'); ?>";
		var image = "<?php echo $this->getSkinUrl('images/collectorbank_ajax/ajax_loader.gif'); ?>";

		var iframeLoaded = false;
		jQuery(document).ready(function() {	
			<?php if (Mage::getStoreConfig('ecomatic_collectorbank/general/customer_type') == 2) {
				if (Mage::getStoreConfig('ecomatic_collectorbank/general/only_unlogged_user')) {
					if (Mage::helper('consumerflow')->isEnabled()) {
						// without setTimeout I end up with infinite loop of calls `setCtype()`
						echo sprintf('setTimeout(function() {setCtype("%s");}, 100);', Mage::helper('consumerflow')->isPrivateMode() ? 'b2c' : 'b2b');
					}  else {
						// without setTimeout I end up with infinite loop of calls `setCtype()`
						echo 'setTimeout(function() {setCtype("b2b");}, 100);';
					}
				}
			?>

				jQuery("#businesstypes a").click(function(e) {
					e.preventDefault();				
					var ctype = jQuery(this).attr('id');
					//      showcartloading();
					setCtype(ctype);
				});
			<?php } elseif (Mage::getStoreConfig('ecomatic_collectorbank/general/customer_type') == 3) { ?>
				setCtype('b2b');
			<?php } else { ?>
				setCtype('b2c');
			<?php } ?>
		});
		function setCtype(ctype) {
			if (iframeLoaded) {
				return;
			}
			jQuery.ajax({
				url:'<?php echo $this->getUrl('ajax/ajax/loadiframe');?>',
				type:'POST',
				dataType: 'json',
				data: {
					ctype: ctype,
				},
				beforeSend: function() {
					// Suspend the Checkout, showing a spinner...
					jQuery('body').addClass('is-suspended');
					try {
						window.collector.checkout.api.suspend();
					}
					catch(err){}
				},
				success:function(data){
					<?php if (Mage::getStoreConfig('ecomatic_collectorbank/general/customer_type') == 2) { ?>
					var result = data;
					if(data.cart_content_ajax){
						jQuery('div.cart').replaceWith(data.cart_content_ajax);
					}
					if(data.iframe_ajax){
						jQuery('div.checkout-iframe').replaceWith(data.iframe_ajax);
					}
					jQuery("#"+ctype ).addClass("active");
					jQuery("#pro-loading").remove();
					jQuery("#pro-img").remove();
					if (ctype == "b2b"){
						jQuery("#b2c").addClass("inactive");
						jQuery("#b2c").removeClass("active");
						jQuery("#b2b").addClass("active");
						jQuery("#b2b").removeClass("inactive");
					}
					else if (ctype == "b2c"){
						jQuery("#b2b").addClass("inactive");
						jQuery("#b2b").removeClass("active");
						jQuery("#b2c").addClass("active");
						jQuery("#b2c").removeClass("inactive");
					}
					<?php } ?>
				},
				complete: function() {
					// ... and finally resume the Checkout after the backend call is completed to update the checkout
					jQuery('body').removeClass('is-suspended');
					window.collector.checkout.api.resume();
					iframeLoaded = true;
				}
			});
		}
	</script>
	
</div>

