
 <?php $_cartQty = $this->getSummaryCount() ?>
        <?php if ($_cartQty == 1): ?>
          <?php echo $this->__('<a title="My Cart (1 item)" class="top-link-cart" href="%s">My Cart (1 item)</a>', $this->getUrl('checkout/cart')) ?>
       <?php else: ?>
          <?php echo $this->__('<a title="My Cart ('.$_cartQty.' items)" class="top-link-cart" href="%s">My Cart (%s items)</a>', $this->getUrl('checkout/cart'), $_cartQty) ?>
  <?php endif; ?>

<?php if(Mage::getStoreConfig('ajax/topcart/enabled')){ ?>

<div class="ajax_topcart" id="ajax_topcart" style="display:none; position:absolute;">
<div class="block top-block-cart">
    <?php $_cartQty = $this->getSummaryCount() ?>
    <div class="block-title">
        <a href="#" onclick="return false;" class="close_ajax_topcart" id="close_ajax_topcart">x</a>
        <strong><span><a href="<?php echo $this->getUrl('checkout/cart');?>"><?php echo $this->__('My Cart') ?></a></span></strong>
    </div>
    <div class="block-content">
    <?php if ($_cartQty>0): ?>
        <div class="summary">
            <?php if ($_cartQty==1): ?>
                <p class="amount"><?php echo $this->__('There is <a href="%s">1 item</a> in your cart.', $this->getUrl('checkout/cart')) ?></p>
            <?php else: ?>
                <p class="amount"><?php echo $this->__('There are <a href="%s">%s items</a> in your cart.', $this->getUrl('checkout/cart'), $_cartQty) ?></p>
            <?php endif ?>
            <p class="subtotal">
                <span class="label"><?php echo $this->__('Cart Subtotal:') ?></span> <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>
                <?php if ($_subtotalInclTax = $this->getSubtotalInclTax()): ?>
                    <br />(<?php echo Mage::helper('checkout')->formatPrice($_subtotalInclTax) ?> <?php echo Mage::helper('tax')->getIncExcText(true) ?>)
                <?php endif; ?>
            </p>
        </div>
    <?php endif ?>
    <?php if($_cartQty && $this->isPossibleOnepageCheckout()): ?>
    <div class="actions">
        <?php echo $this->getChildHtml('extra_actions') ?>
        <button type="button" title="<?php echo $this->__('Checkout') ?>" class="button" onclick="setLocation('<?php echo $this->getCheckoutUrl() ?>')"><span><span><?php echo $this->__('Checkout') ?></span></span></button>
    </div>
    <?php endif ?>
    <?php $_items = $this->getRecentItems() ?>
    <?php if(count($_items)): ?>
        <p class="block-subtitle"><?php echo $this->__('Recently added item(s)') ?></p>
        <ol id="cart-sidebar" class="mini-products-list">
        <?php foreach($_items as $_item): ?>
            <?php echo $this->getItemHtml($_item) ?>
        <?php endforeach; ?>
        </ol>
        <script type="text/javascript">decorateList('cart-sidebar', 'none-recursive')</script>
    <?php else: ?>
        <p class="empty"><?php echo $this->__('You have no items in your shopping cart.') ?></p>
    <?php endif ?>
    </div>
</div>

</div>
<script type="text/javascript">
  var image = "<?php echo $this->getSkinUrl('images/collectorbank_ajax/ajax_loader.gif'); ?>"; 
  var estimateRegionId = "<?php echo $this->getEstimateRegionId() ?>";
  var region_json = <?php echo $this->helper('directory')->getRegionJson() ?>;
  jQuery(document).ready(function()
     {
      jQuery('.fancybox').fancybox({
                                 hideOnContentClick : true,
                  			     width: 520,
                  			     autoDimensions: true,
                                 type : 'iframe',
                  			     showTitle: false,
                  			     scrolling: 'no',
                  			     onComplete: function(){
                  			     	jQuery('#fancybox-frame').load(function() {
                  					jQuery('#fancybox-content').height(jQuery(this).contents().find('body').height()+30);
                  					jQuery.fancybox.resize();
                  				 });
                  			   }
                              });
      });
</script>
<?php } ?>